random_seed = 42
train = true                         # train using default hyperparameters
tune = true                          # tune hyperparameters
evaluate = true
train_size = 0.8
checkpoint_path = "data/checkpoints"

[model]
embedding_dim = 256
hidden_dim = 64
n_layers = 3
output_dim = 1
padding_idx = 0

[optimizer]
lr = 1e-5
momentum = 0.9
weight_decay = 1e-6

[dataloader]
batch_size = 32
num_workers = 0   # > 1 for multiprocessing
pin_memory = true

[trainer]
max_epochs = 10
gradient_clip = 1.0
device = "mps"      # "cpu", "cuda" or "mps"

[tuner]
n_trials = 16

[evaluator]
n_bootstraps = 1000
